/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PwaDebugRouteImport } from './routes/pwa-debug'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth.dashboard.index'
import { Route as AuthDashboardDispatchRouteImport } from './routes/_auth.dashboard.dispatch'
import { Route as AuthDashboardGatePassesRouteImport } from './routes/_auth.dashboard.gate-passes'
import { Route as AuthDashboardGrnRouteImport } from './routes/_auth.dashboard.grn'
import { Route as AuthDashboardHistoryRouteImport } from './routes/_auth.dashboard.history'
import { Route as AuthDashboardInventoryRouteImport } from './routes/_auth.dashboard.inventory'
import { Route as AuthDashboardMarketingRequestsRouteImport } from './routes/_auth.dashboard.marketing-requests'
import { Route as AuthDashboardProductionRouteImport } from './routes/_auth.dashboard.production'
import { Route as AuthDashboardPurchaseOrdersRouteImport } from './routes/_auth.dashboard.purchase-orders'
import { Route as AuthDashboardPurchaseRequestsRouteImport } from './routes/_auth.dashboard.purchase-requests'
import { Route as AuthDashboardReceiptsRouteImport } from './routes/_auth.dashboard.receipts'
import { Route as AuthDashboardRequestsRouteImport } from './routes/_auth.dashboard.requests'
import { Route as AuthDashboardScheduleRouteImport } from './routes/_auth.dashboard.schedule'
import { Route as AuthDashboardSuppliersRouteImport } from './routes/_auth.dashboard.suppliers'
import { Route as AuthDashboardVendorsRouteImport } from './routes/_auth.dashboard.vendors'
import { Route as AuthDashboardAdminBomRouteImport } from './routes/_auth.dashboard.admin.bom'
import { Route as AuthDashboardAdminDepartmentsRouteImport } from './routes/_auth.dashboard.admin.departments'
import { Route as AuthDashboardAdminSettingsRouteImport } from './routes/_auth.dashboard.admin.settings'
import { Route as AuthDashboardAdminUsersRouteImport } from './routes/_auth.dashboard.admin.users'
import { Route as AuthDashboardInventoryIndexRouteImport } from './routes/_auth.dashboard.inventory.index'
import { Route as AuthDashboardInventoryIdRouteImport } from './routes/_auth.dashboard.inventory.$id'
import { Route as AuthDashboardInventoryAttachmentsRouteImport } from './routes/_auth.dashboard.inventory.attachments'
import { Route as AuthDashboardInventoryConsumablesRouteImport } from './routes/_auth.dashboard.inventory.consumables'
import { Route as AuthDashboardInventoryCycleCountRouteImport } from './routes/_auth.dashboard.inventory.cycle-count'
import { Route as AuthDashboardInventoryFinishedGoodsRouteImport } from './routes/_auth.dashboard.inventory.finished-goods'
import { Route as AuthDashboardInventoryNewRouteImport } from './routes/_auth.dashboard.inventory.new'
import { Route as AuthDashboardInventoryRawMaterialsRouteImport } from './routes/_auth.dashboard.inventory.raw-materials'
import { Route as AuthDashboardInventoryScrapsRouteImport } from './routes/_auth.dashboard.inventory.scraps'
import { Route as AuthDashboardInventorySemiFinishedRouteImport } from './routes/_auth.dashboard.inventory.semi-finished'
import { Route as AuthDashboardInventorySparesRouteImport } from './routes/_auth.dashboard.inventory.spares'
import { Route as AuthDashboardInventoryStockAlertsRouteImport } from './routes/_auth.dashboard.inventory.stock-alerts'
import { Route as AuthDashboardInventoryWeedersRouteImport } from './routes/_auth.dashboard.inventory.weeders'
import { Route as AuthDashboardProductionPlanningRouteImport } from './routes/_auth.dashboard.production.planning'
import { Route as AuthDashboardProductionProcessingRouteImport } from './routes/_auth.dashboard.production.processing'
import { Route as AuthDashboardProductionTimeReportRouteImport } from './routes/_auth.dashboard.production.time-report'
import { Route as AuthDashboardScheduleNewRouteImport } from './routes/_auth.dashboard.schedule.new'
import { Route as AuthDashboardSuppliersIdRouteImport } from './routes/_auth.dashboard.suppliers.$id'
import { Route as AuthDashboardVendorsNameRouteImport } from './routes/_auth.dashboard.vendors.$name'
import { Route as AuthDashboardAdminBomNewRouteImport } from './routes/_auth.dashboard.admin.bom.new'
import { Route as AuthDashboardAdminDepartmentsNewRouteImport } from './routes/_auth.dashboard.admin.departments.new'
import { Route as AuthDashboardAdminUsersNewRouteImport } from './routes/_auth.dashboard.admin.users.new'
import { Route as AuthDashboardInventoryIdEditRouteImport } from './routes/_auth.dashboard.inventory.$id.edit'
import { Route as AuthDashboardInventorySparesIdRouteImport } from './routes/_auth.dashboard.inventory.spares.$id'
import { Route as AuthDashboardInventorySparesNewRouteImport } from './routes/_auth.dashboard.inventory.spares.new'
import { Route as AuthDashboardProductionPlanningNewRouteImport } from './routes/_auth.dashboard.production.planning.new'
import { Route as AuthDashboardProductionProcessingIdRouteImport } from './routes/_auth.dashboard.production.processing.$id'
import { Route as AuthDashboardProductionProcessingNewRouteImport } from './routes/_auth.dashboard.production.processing.new'
import { Route as AuthDashboardScheduleIdEditRouteImport } from './routes/_auth.dashboard.schedule.$id.edit'
import { Route as AuthDashboardAdminBomIdEditRouteImport } from './routes/_auth.dashboard.admin.bom.$id.edit'
import { Route as AuthDashboardAdminDepartmentsIdEditRouteImport } from './routes/_auth.dashboard.admin.departments.$id.edit'
import { Route as AuthDashboardAdminUsersIdEditRouteImport } from './routes/_auth.dashboard.admin.users.$id.edit'
import { Route as AuthDashboardProductionPlanningIdEditRouteImport } from './routes/_auth.dashboard.production.planning.$id.edit'
import { Route as AuthDashboardProductionProcessingIdJobsRouteImport } from './routes/_auth.dashboard.production.processing.$id.jobs'
import { Route as AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRouteImport } from './routes/_auth.dashboard.inventory.spares.$id.sub-categories.$subId.items.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PwaDebugRoute = PwaDebugRouteImport.update({
  id: '/pwa-debug',
  path: '/pwa-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardDispatchRoute = AuthDashboardDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardGatePassesRoute = AuthDashboardGatePassesRouteImport.update({
  id: '/gate-passes',
  path: '/gate-passes',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardGrnRoute = AuthDashboardGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardHistoryRoute = AuthDashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardInventoryRoute = AuthDashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardMarketingRequestsRoute =
  AuthDashboardMarketingRequestsRouteImport.update({
    id: '/marketing-requests',
    path: '/marketing-requests',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardProductionRoute = AuthDashboardProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardPurchaseOrdersRoute =
  AuthDashboardPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardPurchaseRequestsRoute =
  AuthDashboardPurchaseRequestsRouteImport.update({
    id: '/purchase-requests',
    path: '/purchase-requests',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardReceiptsRoute = AuthDashboardReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardRequestsRoute = AuthDashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardScheduleRoute = AuthDashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardSuppliersRoute = AuthDashboardSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardVendorsRoute = AuthDashboardVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardAdminBomRoute = AuthDashboardAdminBomRouteImport.update({
  id: '/admin/bom',
  path: '/admin/bom',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardAdminDepartmentsRoute =
  AuthDashboardAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardAdminSettingsRoute =
  AuthDashboardAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardAdminUsersRoute = AuthDashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardInventoryIndexRoute =
  AuthDashboardInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryIdRoute =
  AuthDashboardInventoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryAttachmentsRoute =
  AuthDashboardInventoryAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryConsumablesRoute =
  AuthDashboardInventoryConsumablesRouteImport.update({
    id: '/consumables',
    path: '/consumables',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryCycleCountRoute =
  AuthDashboardInventoryCycleCountRouteImport.update({
    id: '/cycle-count',
    path: '/cycle-count',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryFinishedGoodsRoute =
  AuthDashboardInventoryFinishedGoodsRouteImport.update({
    id: '/finished-goods',
    path: '/finished-goods',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryNewRoute =
  AuthDashboardInventoryNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryRawMaterialsRoute =
  AuthDashboardInventoryRawMaterialsRouteImport.update({
    id: '/raw-materials',
    path: '/raw-materials',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryScrapsRoute =
  AuthDashboardInventoryScrapsRouteImport.update({
    id: '/scraps',
    path: '/scraps',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventorySemiFinishedRoute =
  AuthDashboardInventorySemiFinishedRouteImport.update({
    id: '/semi-finished',
    path: '/semi-finished',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventorySparesRoute =
  AuthDashboardInventorySparesRouteImport.update({
    id: '/spares',
    path: '/spares',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryStockAlertsRoute =
  AuthDashboardInventoryStockAlertsRouteImport.update({
    id: '/stock-alerts',
    path: '/stock-alerts',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardInventoryWeedersRoute =
  AuthDashboardInventoryWeedersRouteImport.update({
    id: '/weeders',
    path: '/weeders',
    getParentRoute: () => AuthDashboardInventoryRoute,
  } as any)
const AuthDashboardProductionPlanningRoute =
  AuthDashboardProductionPlanningRouteImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => AuthDashboardProductionRoute,
  } as any)
const AuthDashboardProductionProcessingRoute =
  AuthDashboardProductionProcessingRouteImport.update({
    id: '/processing',
    path: '/processing',
    getParentRoute: () => AuthDashboardProductionRoute,
  } as any)
const AuthDashboardProductionTimeReportRoute =
  AuthDashboardProductionTimeReportRouteImport.update({
    id: '/time-report',
    path: '/time-report',
    getParentRoute: () => AuthDashboardProductionRoute,
  } as any)
const AuthDashboardScheduleNewRoute =
  AuthDashboardScheduleNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardScheduleRoute,
  } as any)
const AuthDashboardSuppliersIdRoute =
  AuthDashboardSuppliersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthDashboardSuppliersRoute,
  } as any)
const AuthDashboardVendorsNameRoute =
  AuthDashboardVendorsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthDashboardVendorsRoute,
  } as any)
const AuthDashboardAdminBomNewRoute =
  AuthDashboardAdminBomNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardAdminBomRoute,
  } as any)
const AuthDashboardAdminDepartmentsNewRoute =
  AuthDashboardAdminDepartmentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardAdminDepartmentsRoute,
  } as any)
const AuthDashboardAdminUsersNewRoute =
  AuthDashboardAdminUsersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardAdminUsersRoute,
  } as any)
const AuthDashboardInventoryIdEditRoute =
  AuthDashboardInventoryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthDashboardInventoryIdRoute,
  } as any)
const AuthDashboardInventorySparesIdRoute =
  AuthDashboardInventorySparesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthDashboardInventorySparesRoute,
  } as any)
const AuthDashboardInventorySparesNewRoute =
  AuthDashboardInventorySparesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardInventorySparesRoute,
  } as any)
const AuthDashboardProductionPlanningNewRoute =
  AuthDashboardProductionPlanningNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardProductionPlanningRoute,
  } as any)
const AuthDashboardProductionProcessingIdRoute =
  AuthDashboardProductionProcessingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthDashboardProductionProcessingRoute,
  } as any)
const AuthDashboardProductionProcessingNewRoute =
  AuthDashboardProductionProcessingNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthDashboardProductionProcessingRoute,
  } as any)
const AuthDashboardScheduleIdEditRoute =
  AuthDashboardScheduleIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthDashboardScheduleRoute,
  } as any)
const AuthDashboardAdminBomIdEditRoute =
  AuthDashboardAdminBomIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthDashboardAdminBomRoute,
  } as any)
const AuthDashboardAdminDepartmentsIdEditRoute =
  AuthDashboardAdminDepartmentsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthDashboardAdminDepartmentsRoute,
  } as any)
const AuthDashboardAdminUsersIdEditRoute =
  AuthDashboardAdminUsersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthDashboardAdminUsersRoute,
  } as any)
const AuthDashboardProductionPlanningIdEditRoute =
  AuthDashboardProductionPlanningIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthDashboardProductionPlanningRoute,
  } as any)
const AuthDashboardProductionProcessingIdJobsRoute =
  AuthDashboardProductionProcessingIdJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthDashboardProductionProcessingIdRoute,
  } as any)
const AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute =
  AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRouteImport.update({
    id: '/sub-categories/$subId/items/new',
    path: '/sub-categories/$subId/items/new',
    getParentRoute: () => AuthDashboardInventorySparesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pwa-debug': typeof PwaDebugRoute
  '/setup': typeof SetupRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/dashboard/dispatch': typeof AuthDashboardDispatchRoute
  '/dashboard/gate-passes': typeof AuthDashboardGatePassesRoute
  '/dashboard/grn': typeof AuthDashboardGrnRoute
  '/dashboard/history': typeof AuthDashboardHistoryRoute
  '/dashboard/inventory': typeof AuthDashboardInventoryRouteWithChildren
  '/dashboard/marketing-requests': typeof AuthDashboardMarketingRequestsRoute
  '/dashboard/production': typeof AuthDashboardProductionRouteWithChildren
  '/dashboard/purchase-orders': typeof AuthDashboardPurchaseOrdersRoute
  '/dashboard/purchase-requests': typeof AuthDashboardPurchaseRequestsRoute
  '/dashboard/receipts': typeof AuthDashboardReceiptsRoute
  '/dashboard/requests': typeof AuthDashboardRequestsRoute
  '/dashboard/schedule': typeof AuthDashboardScheduleRouteWithChildren
  '/dashboard/suppliers': typeof AuthDashboardSuppliersRouteWithChildren
  '/dashboard/vendors': typeof AuthDashboardVendorsRouteWithChildren
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/admin/bom': typeof AuthDashboardAdminBomRouteWithChildren
  '/dashboard/admin/departments': typeof AuthDashboardAdminDepartmentsRouteWithChildren
  '/dashboard/admin/settings': typeof AuthDashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof AuthDashboardAdminUsersRouteWithChildren
  '/dashboard/inventory/$id': typeof AuthDashboardInventoryIdRouteWithChildren
  '/dashboard/inventory/attachments': typeof AuthDashboardInventoryAttachmentsRoute
  '/dashboard/inventory/consumables': typeof AuthDashboardInventoryConsumablesRoute
  '/dashboard/inventory/cycle-count': typeof AuthDashboardInventoryCycleCountRoute
  '/dashboard/inventory/finished-goods': typeof AuthDashboardInventoryFinishedGoodsRoute
  '/dashboard/inventory/new': typeof AuthDashboardInventoryNewRoute
  '/dashboard/inventory/raw-materials': typeof AuthDashboardInventoryRawMaterialsRoute
  '/dashboard/inventory/scraps': typeof AuthDashboardInventoryScrapsRoute
  '/dashboard/inventory/semi-finished': typeof AuthDashboardInventorySemiFinishedRoute
  '/dashboard/inventory/spares': typeof AuthDashboardInventorySparesRouteWithChildren
  '/dashboard/inventory/stock-alerts': typeof AuthDashboardInventoryStockAlertsRoute
  '/dashboard/inventory/weeders': typeof AuthDashboardInventoryWeedersRoute
  '/dashboard/production/planning': typeof AuthDashboardProductionPlanningRouteWithChildren
  '/dashboard/production/processing': typeof AuthDashboardProductionProcessingRouteWithChildren
  '/dashboard/production/time-report': typeof AuthDashboardProductionTimeReportRoute
  '/dashboard/schedule/new': typeof AuthDashboardScheduleNewRoute
  '/dashboard/suppliers/$id': typeof AuthDashboardSuppliersIdRoute
  '/dashboard/vendors/$name': typeof AuthDashboardVendorsNameRoute
  '/dashboard/inventory/': typeof AuthDashboardInventoryIndexRoute
  '/dashboard/admin/bom/new': typeof AuthDashboardAdminBomNewRoute
  '/dashboard/admin/departments/new': typeof AuthDashboardAdminDepartmentsNewRoute
  '/dashboard/admin/users/new': typeof AuthDashboardAdminUsersNewRoute
  '/dashboard/inventory/$id/edit': typeof AuthDashboardInventoryIdEditRoute
  '/dashboard/inventory/spares/$id': typeof AuthDashboardInventorySparesIdRouteWithChildren
  '/dashboard/inventory/spares/new': typeof AuthDashboardInventorySparesNewRoute
  '/dashboard/production/planning/new': typeof AuthDashboardProductionPlanningNewRoute
  '/dashboard/production/processing/$id': typeof AuthDashboardProductionProcessingIdRouteWithChildren
  '/dashboard/production/processing/new': typeof AuthDashboardProductionProcessingNewRoute
  '/dashboard/schedule/$id/edit': typeof AuthDashboardScheduleIdEditRoute
  '/dashboard/admin/bom/$id/edit': typeof AuthDashboardAdminBomIdEditRoute
  '/dashboard/admin/departments/$id/edit': typeof AuthDashboardAdminDepartmentsIdEditRoute
  '/dashboard/admin/users/$id/edit': typeof AuthDashboardAdminUsersIdEditRoute
  '/dashboard/production/planning/$id/edit': typeof AuthDashboardProductionPlanningIdEditRoute
  '/dashboard/production/processing/$id/jobs': typeof AuthDashboardProductionProcessingIdJobsRoute
  '/dashboard/inventory/spares/$id/sub-categories/$subId/items/new': typeof AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pwa-debug': typeof PwaDebugRoute
  '/setup': typeof SetupRoute
  '/dashboard/dispatch': typeof AuthDashboardDispatchRoute
  '/dashboard/gate-passes': typeof AuthDashboardGatePassesRoute
  '/dashboard/grn': typeof AuthDashboardGrnRoute
  '/dashboard/history': typeof AuthDashboardHistoryRoute
  '/dashboard/marketing-requests': typeof AuthDashboardMarketingRequestsRoute
  '/dashboard/production': typeof AuthDashboardProductionRouteWithChildren
  '/dashboard/purchase-orders': typeof AuthDashboardPurchaseOrdersRoute
  '/dashboard/purchase-requests': typeof AuthDashboardPurchaseRequestsRoute
  '/dashboard/receipts': typeof AuthDashboardReceiptsRoute
  '/dashboard/requests': typeof AuthDashboardRequestsRoute
  '/dashboard/schedule': typeof AuthDashboardScheduleRouteWithChildren
  '/dashboard/suppliers': typeof AuthDashboardSuppliersRouteWithChildren
  '/dashboard/vendors': typeof AuthDashboardVendorsRouteWithChildren
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/admin/bom': typeof AuthDashboardAdminBomRouteWithChildren
  '/dashboard/admin/departments': typeof AuthDashboardAdminDepartmentsRouteWithChildren
  '/dashboard/admin/settings': typeof AuthDashboardAdminSettingsRoute
  '/dashboard/admin/users': typeof AuthDashboardAdminUsersRouteWithChildren
  '/dashboard/inventory/$id': typeof AuthDashboardInventoryIdRouteWithChildren
  '/dashboard/inventory/attachments': typeof AuthDashboardInventoryAttachmentsRoute
  '/dashboard/inventory/consumables': typeof AuthDashboardInventoryConsumablesRoute
  '/dashboard/inventory/cycle-count': typeof AuthDashboardInventoryCycleCountRoute
  '/dashboard/inventory/finished-goods': typeof AuthDashboardInventoryFinishedGoodsRoute
  '/dashboard/inventory/new': typeof AuthDashboardInventoryNewRoute
  '/dashboard/inventory/raw-materials': typeof AuthDashboardInventoryRawMaterialsRoute
  '/dashboard/inventory/scraps': typeof AuthDashboardInventoryScrapsRoute
  '/dashboard/inventory/semi-finished': typeof AuthDashboardInventorySemiFinishedRoute
  '/dashboard/inventory/spares': typeof AuthDashboardInventorySparesRouteWithChildren
  '/dashboard/inventory/stock-alerts': typeof AuthDashboardInventoryStockAlertsRoute
  '/dashboard/inventory/weeders': typeof AuthDashboardInventoryWeedersRoute
  '/dashboard/production/planning': typeof AuthDashboardProductionPlanningRouteWithChildren
  '/dashboard/production/processing': typeof AuthDashboardProductionProcessingRouteWithChildren
  '/dashboard/production/time-report': typeof AuthDashboardProductionTimeReportRoute
  '/dashboard/schedule/new': typeof AuthDashboardScheduleNewRoute
  '/dashboard/suppliers/$id': typeof AuthDashboardSuppliersIdRoute
  '/dashboard/vendors/$name': typeof AuthDashboardVendorsNameRoute
  '/dashboard/inventory': typeof AuthDashboardInventoryIndexRoute
  '/dashboard/admin/bom/new': typeof AuthDashboardAdminBomNewRoute
  '/dashboard/admin/departments/new': typeof AuthDashboardAdminDepartmentsNewRoute
  '/dashboard/admin/users/new': typeof AuthDashboardAdminUsersNewRoute
  '/dashboard/inventory/$id/edit': typeof AuthDashboardInventoryIdEditRoute
  '/dashboard/inventory/spares/$id': typeof AuthDashboardInventorySparesIdRouteWithChildren
  '/dashboard/inventory/spares/new': typeof AuthDashboardInventorySparesNewRoute
  '/dashboard/production/planning/new': typeof AuthDashboardProductionPlanningNewRoute
  '/dashboard/production/processing/$id': typeof AuthDashboardProductionProcessingIdRouteWithChildren
  '/dashboard/production/processing/new': typeof AuthDashboardProductionProcessingNewRoute
  '/dashboard/schedule/$id/edit': typeof AuthDashboardScheduleIdEditRoute
  '/dashboard/admin/bom/$id/edit': typeof AuthDashboardAdminBomIdEditRoute
  '/dashboard/admin/departments/$id/edit': typeof AuthDashboardAdminDepartmentsIdEditRoute
  '/dashboard/admin/users/$id/edit': typeof AuthDashboardAdminUsersIdEditRoute
  '/dashboard/production/planning/$id/edit': typeof AuthDashboardProductionPlanningIdEditRoute
  '/dashboard/production/processing/$id/jobs': typeof AuthDashboardProductionProcessingIdJobsRoute
  '/dashboard/inventory/spares/$id/sub-categories/$subId/items/new': typeof AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/pwa-debug': typeof PwaDebugRoute
  '/setup': typeof SetupRoute
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/dashboard/dispatch': typeof AuthDashboardDispatchRoute
  '/_auth/dashboard/gate-passes': typeof AuthDashboardGatePassesRoute
  '/_auth/dashboard/grn': typeof AuthDashboardGrnRoute
  '/_auth/dashboard/history': typeof AuthDashboardHistoryRoute
  '/_auth/dashboard/inventory': typeof AuthDashboardInventoryRouteWithChildren
  '/_auth/dashboard/marketing-requests': typeof AuthDashboardMarketingRequestsRoute
  '/_auth/dashboard/production': typeof AuthDashboardProductionRouteWithChildren
  '/_auth/dashboard/purchase-orders': typeof AuthDashboardPurchaseOrdersRoute
  '/_auth/dashboard/purchase-requests': typeof AuthDashboardPurchaseRequestsRoute
  '/_auth/dashboard/receipts': typeof AuthDashboardReceiptsRoute
  '/_auth/dashboard/requests': typeof AuthDashboardRequestsRoute
  '/_auth/dashboard/schedule': typeof AuthDashboardScheduleRouteWithChildren
  '/_auth/dashboard/suppliers': typeof AuthDashboardSuppliersRouteWithChildren
  '/_auth/dashboard/vendors': typeof AuthDashboardVendorsRouteWithChildren
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/admin/bom': typeof AuthDashboardAdminBomRouteWithChildren
  '/_auth/dashboard/admin/departments': typeof AuthDashboardAdminDepartmentsRouteWithChildren
  '/_auth/dashboard/admin/settings': typeof AuthDashboardAdminSettingsRoute
  '/_auth/dashboard/admin/users': typeof AuthDashboardAdminUsersRouteWithChildren
  '/_auth/dashboard/inventory/$id': typeof AuthDashboardInventoryIdRouteWithChildren
  '/_auth/dashboard/inventory/attachments': typeof AuthDashboardInventoryAttachmentsRoute
  '/_auth/dashboard/inventory/consumables': typeof AuthDashboardInventoryConsumablesRoute
  '/_auth/dashboard/inventory/cycle-count': typeof AuthDashboardInventoryCycleCountRoute
  '/_auth/dashboard/inventory/finished-goods': typeof AuthDashboardInventoryFinishedGoodsRoute
  '/_auth/dashboard/inventory/new': typeof AuthDashboardInventoryNewRoute
  '/_auth/dashboard/inventory/raw-materials': typeof AuthDashboardInventoryRawMaterialsRoute
  '/_auth/dashboard/inventory/scraps': typeof AuthDashboardInventoryScrapsRoute
  '/_auth/dashboard/inventory/semi-finished': typeof AuthDashboardInventorySemiFinishedRoute
  '/_auth/dashboard/inventory/spares': typeof AuthDashboardInventorySparesRouteWithChildren
  '/_auth/dashboard/inventory/stock-alerts': typeof AuthDashboardInventoryStockAlertsRoute
  '/_auth/dashboard/inventory/weeders': typeof AuthDashboardInventoryWeedersRoute
  '/_auth/dashboard/production/planning': typeof AuthDashboardProductionPlanningRouteWithChildren
  '/_auth/dashboard/production/processing': typeof AuthDashboardProductionProcessingRouteWithChildren
  '/_auth/dashboard/production/time-report': typeof AuthDashboardProductionTimeReportRoute
  '/_auth/dashboard/schedule/new': typeof AuthDashboardScheduleNewRoute
  '/_auth/dashboard/suppliers/$id': typeof AuthDashboardSuppliersIdRoute
  '/_auth/dashboard/vendors/$name': typeof AuthDashboardVendorsNameRoute
  '/_auth/dashboard/inventory/': typeof AuthDashboardInventoryIndexRoute
  '/_auth/dashboard/admin/bom/new': typeof AuthDashboardAdminBomNewRoute
  '/_auth/dashboard/admin/departments/new': typeof AuthDashboardAdminDepartmentsNewRoute
  '/_auth/dashboard/admin/users/new': typeof AuthDashboardAdminUsersNewRoute
  '/_auth/dashboard/inventory/$id/edit': typeof AuthDashboardInventoryIdEditRoute
  '/_auth/dashboard/inventory/spares/$id': typeof AuthDashboardInventorySparesIdRouteWithChildren
  '/_auth/dashboard/inventory/spares/new': typeof AuthDashboardInventorySparesNewRoute
  '/_auth/dashboard/production/planning/new': typeof AuthDashboardProductionPlanningNewRoute
  '/_auth/dashboard/production/processing/$id': typeof AuthDashboardProductionProcessingIdRouteWithChildren
  '/_auth/dashboard/production/processing/new': typeof AuthDashboardProductionProcessingNewRoute
  '/_auth/dashboard/schedule/$id/edit': typeof AuthDashboardScheduleIdEditRoute
  '/_auth/dashboard/admin/bom/$id/edit': typeof AuthDashboardAdminBomIdEditRoute
  '/_auth/dashboard/admin/departments/$id/edit': typeof AuthDashboardAdminDepartmentsIdEditRoute
  '/_auth/dashboard/admin/users/$id/edit': typeof AuthDashboardAdminUsersIdEditRoute
  '/_auth/dashboard/production/planning/$id/edit': typeof AuthDashboardProductionPlanningIdEditRoute
  '/_auth/dashboard/production/processing/$id/jobs': typeof AuthDashboardProductionProcessingIdJobsRoute
  '/_auth/dashboard/inventory/spares/$id/sub-categories/$subId/items/new': typeof AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pwa-debug'
    | '/setup'
    | '/dashboard'
    | '/dashboard/dispatch'
    | '/dashboard/gate-passes'
    | '/dashboard/grn'
    | '/dashboard/history'
    | '/dashboard/inventory'
    | '/dashboard/marketing-requests'
    | '/dashboard/production'
    | '/dashboard/purchase-orders'
    | '/dashboard/purchase-requests'
    | '/dashboard/receipts'
    | '/dashboard/requests'
    | '/dashboard/schedule'
    | '/dashboard/suppliers'
    | '/dashboard/vendors'
    | '/dashboard/'
    | '/dashboard/admin/bom'
    | '/dashboard/admin/departments'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/attachments'
    | '/dashboard/inventory/consumables'
    | '/dashboard/inventory/cycle-count'
    | '/dashboard/inventory/finished-goods'
    | '/dashboard/inventory/new'
    | '/dashboard/inventory/raw-materials'
    | '/dashboard/inventory/scraps'
    | '/dashboard/inventory/semi-finished'
    | '/dashboard/inventory/spares'
    | '/dashboard/inventory/stock-alerts'
    | '/dashboard/inventory/weeders'
    | '/dashboard/production/planning'
    | '/dashboard/production/processing'
    | '/dashboard/production/time-report'
    | '/dashboard/schedule/new'
    | '/dashboard/suppliers/$id'
    | '/dashboard/vendors/$name'
    | '/dashboard/inventory/'
    | '/dashboard/admin/bom/new'
    | '/dashboard/admin/departments/new'
    | '/dashboard/admin/users/new'
    | '/dashboard/inventory/$id/edit'
    | '/dashboard/inventory/spares/$id'
    | '/dashboard/inventory/spares/new'
    | '/dashboard/production/planning/new'
    | '/dashboard/production/processing/$id'
    | '/dashboard/production/processing/new'
    | '/dashboard/schedule/$id/edit'
    | '/dashboard/admin/bom/$id/edit'
    | '/dashboard/admin/departments/$id/edit'
    | '/dashboard/admin/users/$id/edit'
    | '/dashboard/production/planning/$id/edit'
    | '/dashboard/production/processing/$id/jobs'
    | '/dashboard/inventory/spares/$id/sub-categories/$subId/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pwa-debug'
    | '/setup'
    | '/dashboard/dispatch'
    | '/dashboard/gate-passes'
    | '/dashboard/grn'
    | '/dashboard/history'
    | '/dashboard/marketing-requests'
    | '/dashboard/production'
    | '/dashboard/purchase-orders'
    | '/dashboard/purchase-requests'
    | '/dashboard/receipts'
    | '/dashboard/requests'
    | '/dashboard/schedule'
    | '/dashboard/suppliers'
    | '/dashboard/vendors'
    | '/dashboard'
    | '/dashboard/admin/bom'
    | '/dashboard/admin/departments'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/users'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/attachments'
    | '/dashboard/inventory/consumables'
    | '/dashboard/inventory/cycle-count'
    | '/dashboard/inventory/finished-goods'
    | '/dashboard/inventory/new'
    | '/dashboard/inventory/raw-materials'
    | '/dashboard/inventory/scraps'
    | '/dashboard/inventory/semi-finished'
    | '/dashboard/inventory/spares'
    | '/dashboard/inventory/stock-alerts'
    | '/dashboard/inventory/weeders'
    | '/dashboard/production/planning'
    | '/dashboard/production/processing'
    | '/dashboard/production/time-report'
    | '/dashboard/schedule/new'
    | '/dashboard/suppliers/$id'
    | '/dashboard/vendors/$name'
    | '/dashboard/inventory'
    | '/dashboard/admin/bom/new'
    | '/dashboard/admin/departments/new'
    | '/dashboard/admin/users/new'
    | '/dashboard/inventory/$id/edit'
    | '/dashboard/inventory/spares/$id'
    | '/dashboard/inventory/spares/new'
    | '/dashboard/production/planning/new'
    | '/dashboard/production/processing/$id'
    | '/dashboard/production/processing/new'
    | '/dashboard/schedule/$id/edit'
    | '/dashboard/admin/bom/$id/edit'
    | '/dashboard/admin/departments/$id/edit'
    | '/dashboard/admin/users/$id/edit'
    | '/dashboard/production/planning/$id/edit'
    | '/dashboard/production/processing/$id/jobs'
    | '/dashboard/inventory/spares/$id/sub-categories/$subId/items/new'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/pwa-debug'
    | '/setup'
    | '/_auth/dashboard'
    | '/_auth/dashboard/dispatch'
    | '/_auth/dashboard/gate-passes'
    | '/_auth/dashboard/grn'
    | '/_auth/dashboard/history'
    | '/_auth/dashboard/inventory'
    | '/_auth/dashboard/marketing-requests'
    | '/_auth/dashboard/production'
    | '/_auth/dashboard/purchase-orders'
    | '/_auth/dashboard/purchase-requests'
    | '/_auth/dashboard/receipts'
    | '/_auth/dashboard/requests'
    | '/_auth/dashboard/schedule'
    | '/_auth/dashboard/suppliers'
    | '/_auth/dashboard/vendors'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/admin/bom'
    | '/_auth/dashboard/admin/departments'
    | '/_auth/dashboard/admin/settings'
    | '/_auth/dashboard/admin/users'
    | '/_auth/dashboard/inventory/$id'
    | '/_auth/dashboard/inventory/attachments'
    | '/_auth/dashboard/inventory/consumables'
    | '/_auth/dashboard/inventory/cycle-count'
    | '/_auth/dashboard/inventory/finished-goods'
    | '/_auth/dashboard/inventory/new'
    | '/_auth/dashboard/inventory/raw-materials'
    | '/_auth/dashboard/inventory/scraps'
    | '/_auth/dashboard/inventory/semi-finished'
    | '/_auth/dashboard/inventory/spares'
    | '/_auth/dashboard/inventory/stock-alerts'
    | '/_auth/dashboard/inventory/weeders'
    | '/_auth/dashboard/production/planning'
    | '/_auth/dashboard/production/processing'
    | '/_auth/dashboard/production/time-report'
    | '/_auth/dashboard/schedule/new'
    | '/_auth/dashboard/suppliers/$id'
    | '/_auth/dashboard/vendors/$name'
    | '/_auth/dashboard/inventory/'
    | '/_auth/dashboard/admin/bom/new'
    | '/_auth/dashboard/admin/departments/new'
    | '/_auth/dashboard/admin/users/new'
    | '/_auth/dashboard/inventory/$id/edit'
    | '/_auth/dashboard/inventory/spares/$id'
    | '/_auth/dashboard/inventory/spares/new'
    | '/_auth/dashboard/production/planning/new'
    | '/_auth/dashboard/production/processing/$id'
    | '/_auth/dashboard/production/processing/new'
    | '/_auth/dashboard/schedule/$id/edit'
    | '/_auth/dashboard/admin/bom/$id/edit'
    | '/_auth/dashboard/admin/departments/$id/edit'
    | '/_auth/dashboard/admin/users/$id/edit'
    | '/_auth/dashboard/production/planning/$id/edit'
    | '/_auth/dashboard/production/processing/$id/jobs'
    | '/_auth/dashboard/inventory/spares/$id/sub-categories/$subId/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PwaDebugRoute: typeof PwaDebugRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pwa-debug': {
      id: '/pwa-debug'
      path: '/pwa-debug'
      fullPath: '/pwa-debug'
      preLoaderRoute: typeof PwaDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/dispatch': {
      id: '/_auth/dashboard/dispatch'
      path: '/dispatch'
      fullPath: '/dashboard/dispatch'
      preLoaderRoute: typeof AuthDashboardDispatchRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/gate-passes': {
      id: '/_auth/dashboard/gate-passes'
      path: '/gate-passes'
      fullPath: '/dashboard/gate-passes'
      preLoaderRoute: typeof AuthDashboardGatePassesRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/grn': {
      id: '/_auth/dashboard/grn'
      path: '/grn'
      fullPath: '/dashboard/grn'
      preLoaderRoute: typeof AuthDashboardGrnRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/history': {
      id: '/_auth/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthDashboardHistoryRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/inventory': {
      id: '/_auth/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof AuthDashboardInventoryRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/marketing-requests': {
      id: '/_auth/dashboard/marketing-requests'
      path: '/marketing-requests'
      fullPath: '/dashboard/marketing-requests'
      preLoaderRoute: typeof AuthDashboardMarketingRequestsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/production': {
      id: '/_auth/dashboard/production'
      path: '/production'
      fullPath: '/dashboard/production'
      preLoaderRoute: typeof AuthDashboardProductionRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/purchase-orders': {
      id: '/_auth/dashboard/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/dashboard/purchase-orders'
      preLoaderRoute: typeof AuthDashboardPurchaseOrdersRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/purchase-requests': {
      id: '/_auth/dashboard/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/dashboard/purchase-requests'
      preLoaderRoute: typeof AuthDashboardPurchaseRequestsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/receipts': {
      id: '/_auth/dashboard/receipts'
      path: '/receipts'
      fullPath: '/dashboard/receipts'
      preLoaderRoute: typeof AuthDashboardReceiptsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/requests': {
      id: '/_auth/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof AuthDashboardRequestsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/schedule': {
      id: '/_auth/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof AuthDashboardScheduleRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/suppliers': {
      id: '/_auth/dashboard/suppliers'
      path: '/suppliers'
      fullPath: '/dashboard/suppliers'
      preLoaderRoute: typeof AuthDashboardSuppliersRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/vendors': {
      id: '/_auth/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof AuthDashboardVendorsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/admin/bom': {
      id: '/_auth/dashboard/admin/bom'
      path: '/admin/bom'
      fullPath: '/dashboard/admin/bom'
      preLoaderRoute: typeof AuthDashboardAdminBomRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/admin/departments': {
      id: '/_auth/dashboard/admin/departments'
      path: '/admin/departments'
      fullPath: '/dashboard/admin/departments'
      preLoaderRoute: typeof AuthDashboardAdminDepartmentsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/admin/settings': {
      id: '/_auth/dashboard/admin/settings'
      path: '/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof AuthDashboardAdminSettingsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/admin/users': {
      id: '/_auth/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthDashboardAdminUsersRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/inventory/': {
      id: '/_auth/dashboard/inventory/'
      path: '/'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof AuthDashboardInventoryIndexRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/$id': {
      id: '/_auth/dashboard/inventory/$id'
      path: '/$id'
      fullPath: '/dashboard/inventory/$id'
      preLoaderRoute: typeof AuthDashboardInventoryIdRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/attachments': {
      id: '/_auth/dashboard/inventory/attachments'
      path: '/attachments'
      fullPath: '/dashboard/inventory/attachments'
      preLoaderRoute: typeof AuthDashboardInventoryAttachmentsRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/consumables': {
      id: '/_auth/dashboard/inventory/consumables'
      path: '/consumables'
      fullPath: '/dashboard/inventory/consumables'
      preLoaderRoute: typeof AuthDashboardInventoryConsumablesRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/cycle-count': {
      id: '/_auth/dashboard/inventory/cycle-count'
      path: '/cycle-count'
      fullPath: '/dashboard/inventory/cycle-count'
      preLoaderRoute: typeof AuthDashboardInventoryCycleCountRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/finished-goods': {
      id: '/_auth/dashboard/inventory/finished-goods'
      path: '/finished-goods'
      fullPath: '/dashboard/inventory/finished-goods'
      preLoaderRoute: typeof AuthDashboardInventoryFinishedGoodsRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/new': {
      id: '/_auth/dashboard/inventory/new'
      path: '/new'
      fullPath: '/dashboard/inventory/new'
      preLoaderRoute: typeof AuthDashboardInventoryNewRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/raw-materials': {
      id: '/_auth/dashboard/inventory/raw-materials'
      path: '/raw-materials'
      fullPath: '/dashboard/inventory/raw-materials'
      preLoaderRoute: typeof AuthDashboardInventoryRawMaterialsRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/scraps': {
      id: '/_auth/dashboard/inventory/scraps'
      path: '/scraps'
      fullPath: '/dashboard/inventory/scraps'
      preLoaderRoute: typeof AuthDashboardInventoryScrapsRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/semi-finished': {
      id: '/_auth/dashboard/inventory/semi-finished'
      path: '/semi-finished'
      fullPath: '/dashboard/inventory/semi-finished'
      preLoaderRoute: typeof AuthDashboardInventorySemiFinishedRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/spares': {
      id: '/_auth/dashboard/inventory/spares'
      path: '/spares'
      fullPath: '/dashboard/inventory/spares'
      preLoaderRoute: typeof AuthDashboardInventorySparesRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/stock-alerts': {
      id: '/_auth/dashboard/inventory/stock-alerts'
      path: '/stock-alerts'
      fullPath: '/dashboard/inventory/stock-alerts'
      preLoaderRoute: typeof AuthDashboardInventoryStockAlertsRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/inventory/weeders': {
      id: '/_auth/dashboard/inventory/weeders'
      path: '/weeders'
      fullPath: '/dashboard/inventory/weeders'
      preLoaderRoute: typeof AuthDashboardInventoryWeedersRouteImport
      parentRoute: typeof AuthDashboardInventoryRoute
    }
    '/_auth/dashboard/production/planning': {
      id: '/_auth/dashboard/production/planning'
      path: '/planning'
      fullPath: '/dashboard/production/planning'
      preLoaderRoute: typeof AuthDashboardProductionPlanningRouteImport
      parentRoute: typeof AuthDashboardProductionRoute
    }
    '/_auth/dashboard/production/processing': {
      id: '/_auth/dashboard/production/processing'
      path: '/processing'
      fullPath: '/dashboard/production/processing'
      preLoaderRoute: typeof AuthDashboardProductionProcessingRouteImport
      parentRoute: typeof AuthDashboardProductionRoute
    }
    '/_auth/dashboard/production/time-report': {
      id: '/_auth/dashboard/production/time-report'
      path: '/time-report'
      fullPath: '/dashboard/production/time-report'
      preLoaderRoute: typeof AuthDashboardProductionTimeReportRouteImport
      parentRoute: typeof AuthDashboardProductionRoute
    }
    '/_auth/dashboard/schedule/new': {
      id: '/_auth/dashboard/schedule/new'
      path: '/new'
      fullPath: '/dashboard/schedule/new'
      preLoaderRoute: typeof AuthDashboardScheduleNewRouteImport
      parentRoute: typeof AuthDashboardScheduleRoute
    }
    '/_auth/dashboard/suppliers/$id': {
      id: '/_auth/dashboard/suppliers/$id'
      path: '/$id'
      fullPath: '/dashboard/suppliers/$id'
      preLoaderRoute: typeof AuthDashboardSuppliersIdRouteImport
      parentRoute: typeof AuthDashboardSuppliersRoute
    }
    '/_auth/dashboard/vendors/$name': {
      id: '/_auth/dashboard/vendors/$name'
      path: '/$name'
      fullPath: '/dashboard/vendors/$name'
      preLoaderRoute: typeof AuthDashboardVendorsNameRouteImport
      parentRoute: typeof AuthDashboardVendorsRoute
    }
    '/_auth/dashboard/admin/bom/new': {
      id: '/_auth/dashboard/admin/bom/new'
      path: '/new'
      fullPath: '/dashboard/admin/bom/new'
      preLoaderRoute: typeof AuthDashboardAdminBomNewRouteImport
      parentRoute: typeof AuthDashboardAdminBomRoute
    }
    '/_auth/dashboard/admin/departments/new': {
      id: '/_auth/dashboard/admin/departments/new'
      path: '/new'
      fullPath: '/dashboard/admin/departments/new'
      preLoaderRoute: typeof AuthDashboardAdminDepartmentsNewRouteImport
      parentRoute: typeof AuthDashboardAdminDepartmentsRoute
    }
    '/_auth/dashboard/admin/users/new': {
      id: '/_auth/dashboard/admin/users/new'
      path: '/new'
      fullPath: '/dashboard/admin/users/new'
      preLoaderRoute: typeof AuthDashboardAdminUsersNewRouteImport
      parentRoute: typeof AuthDashboardAdminUsersRoute
    }
    '/_auth/dashboard/inventory/$id/edit': {
      id: '/_auth/dashboard/inventory/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/inventory/$id/edit'
      preLoaderRoute: typeof AuthDashboardInventoryIdEditRouteImport
      parentRoute: typeof AuthDashboardInventoryIdRoute
    }
    '/_auth/dashboard/inventory/spares/$id': {
      id: '/_auth/dashboard/inventory/spares/$id'
      path: '/$id'
      fullPath: '/dashboard/inventory/spares/$id'
      preLoaderRoute: typeof AuthDashboardInventorySparesIdRouteImport
      parentRoute: typeof AuthDashboardInventorySparesRoute
    }
    '/_auth/dashboard/inventory/spares/new': {
      id: '/_auth/dashboard/inventory/spares/new'
      path: '/new'
      fullPath: '/dashboard/inventory/spares/new'
      preLoaderRoute: typeof AuthDashboardInventorySparesNewRouteImport
      parentRoute: typeof AuthDashboardInventorySparesRoute
    }
    '/_auth/dashboard/production/planning/new': {
      id: '/_auth/dashboard/production/planning/new'
      path: '/new'
      fullPath: '/dashboard/production/planning/new'
      preLoaderRoute: typeof AuthDashboardProductionPlanningNewRouteImport
      parentRoute: typeof AuthDashboardProductionPlanningRoute
    }
    '/_auth/dashboard/production/processing/$id': {
      id: '/_auth/dashboard/production/processing/$id'
      path: '/$id'
      fullPath: '/dashboard/production/processing/$id'
      preLoaderRoute: typeof AuthDashboardProductionProcessingIdRouteImport
      parentRoute: typeof AuthDashboardProductionProcessingRoute
    }
    '/_auth/dashboard/production/processing/new': {
      id: '/_auth/dashboard/production/processing/new'
      path: '/new'
      fullPath: '/dashboard/production/processing/new'
      preLoaderRoute: typeof AuthDashboardProductionProcessingNewRouteImport
      parentRoute: typeof AuthDashboardProductionProcessingRoute
    }
    '/_auth/dashboard/schedule/$id/edit': {
      id: '/_auth/dashboard/schedule/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/schedule/$id/edit'
      preLoaderRoute: typeof AuthDashboardScheduleIdEditRouteImport
      parentRoute: typeof AuthDashboardScheduleRoute
    }
    '/_auth/dashboard/admin/bom/$id/edit': {
      id: '/_auth/dashboard/admin/bom/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/admin/bom/$id/edit'
      preLoaderRoute: typeof AuthDashboardAdminBomIdEditRouteImport
      parentRoute: typeof AuthDashboardAdminBomRoute
    }
    '/_auth/dashboard/admin/departments/$id/edit': {
      id: '/_auth/dashboard/admin/departments/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/admin/departments/$id/edit'
      preLoaderRoute: typeof AuthDashboardAdminDepartmentsIdEditRouteImport
      parentRoute: typeof AuthDashboardAdminDepartmentsRoute
    }
    '/_auth/dashboard/admin/users/$id/edit': {
      id: '/_auth/dashboard/admin/users/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/admin/users/$id/edit'
      preLoaderRoute: typeof AuthDashboardAdminUsersIdEditRouteImport
      parentRoute: typeof AuthDashboardAdminUsersRoute
    }
    '/_auth/dashboard/production/planning/$id/edit': {
      id: '/_auth/dashboard/production/planning/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/production/planning/$id/edit'
      preLoaderRoute: typeof AuthDashboardProductionPlanningIdEditRouteImport
      parentRoute: typeof AuthDashboardProductionPlanningRoute
    }
    '/_auth/dashboard/production/processing/$id/jobs': {
      id: '/_auth/dashboard/production/processing/$id/jobs'
      path: '/jobs'
      fullPath: '/dashboard/production/processing/$id/jobs'
      preLoaderRoute: typeof AuthDashboardProductionProcessingIdJobsRouteImport
      parentRoute: typeof AuthDashboardProductionProcessingIdRoute
    }
    '/_auth/dashboard/inventory/spares/$id/sub-categories/$subId/items/new': {
      id: '/_auth/dashboard/inventory/spares/$id/sub-categories/$subId/items/new'
      path: '/sub-categories/$subId/items/new'
      fullPath: '/dashboard/inventory/spares/$id/sub-categories/$subId/items/new'
      preLoaderRoute: typeof AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRouteImport
      parentRoute: typeof AuthDashboardInventorySparesIdRoute
    }
  }
}

interface AuthDashboardInventoryIdRouteChildren {
  AuthDashboardInventoryIdEditRoute: typeof AuthDashboardInventoryIdEditRoute
}

const AuthDashboardInventoryIdRouteChildren: AuthDashboardInventoryIdRouteChildren =
  {
    AuthDashboardInventoryIdEditRoute: AuthDashboardInventoryIdEditRoute,
  }

const AuthDashboardInventoryIdRouteWithChildren =
  AuthDashboardInventoryIdRoute._addFileChildren(
    AuthDashboardInventoryIdRouteChildren,
  )

interface AuthDashboardInventorySparesIdRouteChildren {
  AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute: typeof AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute
}

const AuthDashboardInventorySparesIdRouteChildren: AuthDashboardInventorySparesIdRouteChildren =
  {
    AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute:
      AuthDashboardInventorySparesIdSubCategoriesSubIdItemsNewRoute,
  }

const AuthDashboardInventorySparesIdRouteWithChildren =
  AuthDashboardInventorySparesIdRoute._addFileChildren(
    AuthDashboardInventorySparesIdRouteChildren,
  )

interface AuthDashboardInventorySparesRouteChildren {
  AuthDashboardInventorySparesIdRoute: typeof AuthDashboardInventorySparesIdRouteWithChildren
  AuthDashboardInventorySparesNewRoute: typeof AuthDashboardInventorySparesNewRoute
}

const AuthDashboardInventorySparesRouteChildren: AuthDashboardInventorySparesRouteChildren =
  {
    AuthDashboardInventorySparesIdRoute:
      AuthDashboardInventorySparesIdRouteWithChildren,
    AuthDashboardInventorySparesNewRoute: AuthDashboardInventorySparesNewRoute,
  }

const AuthDashboardInventorySparesRouteWithChildren =
  AuthDashboardInventorySparesRoute._addFileChildren(
    AuthDashboardInventorySparesRouteChildren,
  )

interface AuthDashboardInventoryRouteChildren {
  AuthDashboardInventoryIdRoute: typeof AuthDashboardInventoryIdRouteWithChildren
  AuthDashboardInventoryAttachmentsRoute: typeof AuthDashboardInventoryAttachmentsRoute
  AuthDashboardInventoryConsumablesRoute: typeof AuthDashboardInventoryConsumablesRoute
  AuthDashboardInventoryCycleCountRoute: typeof AuthDashboardInventoryCycleCountRoute
  AuthDashboardInventoryFinishedGoodsRoute: typeof AuthDashboardInventoryFinishedGoodsRoute
  AuthDashboardInventoryNewRoute: typeof AuthDashboardInventoryNewRoute
  AuthDashboardInventoryRawMaterialsRoute: typeof AuthDashboardInventoryRawMaterialsRoute
  AuthDashboardInventoryScrapsRoute: typeof AuthDashboardInventoryScrapsRoute
  AuthDashboardInventorySemiFinishedRoute: typeof AuthDashboardInventorySemiFinishedRoute
  AuthDashboardInventorySparesRoute: typeof AuthDashboardInventorySparesRouteWithChildren
  AuthDashboardInventoryStockAlertsRoute: typeof AuthDashboardInventoryStockAlertsRoute
  AuthDashboardInventoryWeedersRoute: typeof AuthDashboardInventoryWeedersRoute
  AuthDashboardInventoryIndexRoute: typeof AuthDashboardInventoryIndexRoute
}

const AuthDashboardInventoryRouteChildren: AuthDashboardInventoryRouteChildren =
  {
    AuthDashboardInventoryIdRoute: AuthDashboardInventoryIdRouteWithChildren,
    AuthDashboardInventoryAttachmentsRoute:
      AuthDashboardInventoryAttachmentsRoute,
    AuthDashboardInventoryConsumablesRoute:
      AuthDashboardInventoryConsumablesRoute,
    AuthDashboardInventoryCycleCountRoute:
      AuthDashboardInventoryCycleCountRoute,
    AuthDashboardInventoryFinishedGoodsRoute:
      AuthDashboardInventoryFinishedGoodsRoute,
    AuthDashboardInventoryNewRoute: AuthDashboardInventoryNewRoute,
    AuthDashboardInventoryRawMaterialsRoute:
      AuthDashboardInventoryRawMaterialsRoute,
    AuthDashboardInventoryScrapsRoute: AuthDashboardInventoryScrapsRoute,
    AuthDashboardInventorySemiFinishedRoute:
      AuthDashboardInventorySemiFinishedRoute,
    AuthDashboardInventorySparesRoute:
      AuthDashboardInventorySparesRouteWithChildren,
    AuthDashboardInventoryStockAlertsRoute:
      AuthDashboardInventoryStockAlertsRoute,
    AuthDashboardInventoryWeedersRoute: AuthDashboardInventoryWeedersRoute,
    AuthDashboardInventoryIndexRoute: AuthDashboardInventoryIndexRoute,
  }

const AuthDashboardInventoryRouteWithChildren =
  AuthDashboardInventoryRoute._addFileChildren(
    AuthDashboardInventoryRouteChildren,
  )

interface AuthDashboardProductionPlanningRouteChildren {
  AuthDashboardProductionPlanningNewRoute: typeof AuthDashboardProductionPlanningNewRoute
  AuthDashboardProductionPlanningIdEditRoute: typeof AuthDashboardProductionPlanningIdEditRoute
}

const AuthDashboardProductionPlanningRouteChildren: AuthDashboardProductionPlanningRouteChildren =
  {
    AuthDashboardProductionPlanningNewRoute:
      AuthDashboardProductionPlanningNewRoute,
    AuthDashboardProductionPlanningIdEditRoute:
      AuthDashboardProductionPlanningIdEditRoute,
  }

const AuthDashboardProductionPlanningRouteWithChildren =
  AuthDashboardProductionPlanningRoute._addFileChildren(
    AuthDashboardProductionPlanningRouteChildren,
  )

interface AuthDashboardProductionProcessingIdRouteChildren {
  AuthDashboardProductionProcessingIdJobsRoute: typeof AuthDashboardProductionProcessingIdJobsRoute
}

const AuthDashboardProductionProcessingIdRouteChildren: AuthDashboardProductionProcessingIdRouteChildren =
  {
    AuthDashboardProductionProcessingIdJobsRoute:
      AuthDashboardProductionProcessingIdJobsRoute,
  }

const AuthDashboardProductionProcessingIdRouteWithChildren =
  AuthDashboardProductionProcessingIdRoute._addFileChildren(
    AuthDashboardProductionProcessingIdRouteChildren,
  )

interface AuthDashboardProductionProcessingRouteChildren {
  AuthDashboardProductionProcessingIdRoute: typeof AuthDashboardProductionProcessingIdRouteWithChildren
  AuthDashboardProductionProcessingNewRoute: typeof AuthDashboardProductionProcessingNewRoute
}

const AuthDashboardProductionProcessingRouteChildren: AuthDashboardProductionProcessingRouteChildren =
  {
    AuthDashboardProductionProcessingIdRoute:
      AuthDashboardProductionProcessingIdRouteWithChildren,
    AuthDashboardProductionProcessingNewRoute:
      AuthDashboardProductionProcessingNewRoute,
  }

const AuthDashboardProductionProcessingRouteWithChildren =
  AuthDashboardProductionProcessingRoute._addFileChildren(
    AuthDashboardProductionProcessingRouteChildren,
  )

interface AuthDashboardProductionRouteChildren {
  AuthDashboardProductionPlanningRoute: typeof AuthDashboardProductionPlanningRouteWithChildren
  AuthDashboardProductionProcessingRoute: typeof AuthDashboardProductionProcessingRouteWithChildren
  AuthDashboardProductionTimeReportRoute: typeof AuthDashboardProductionTimeReportRoute
}

const AuthDashboardProductionRouteChildren: AuthDashboardProductionRouteChildren =
  {
    AuthDashboardProductionPlanningRoute:
      AuthDashboardProductionPlanningRouteWithChildren,
    AuthDashboardProductionProcessingRoute:
      AuthDashboardProductionProcessingRouteWithChildren,
    AuthDashboardProductionTimeReportRoute:
      AuthDashboardProductionTimeReportRoute,
  }

const AuthDashboardProductionRouteWithChildren =
  AuthDashboardProductionRoute._addFileChildren(
    AuthDashboardProductionRouteChildren,
  )

interface AuthDashboardScheduleRouteChildren {
  AuthDashboardScheduleNewRoute: typeof AuthDashboardScheduleNewRoute
  AuthDashboardScheduleIdEditRoute: typeof AuthDashboardScheduleIdEditRoute
}

const AuthDashboardScheduleRouteChildren: AuthDashboardScheduleRouteChildren = {
  AuthDashboardScheduleNewRoute: AuthDashboardScheduleNewRoute,
  AuthDashboardScheduleIdEditRoute: AuthDashboardScheduleIdEditRoute,
}

const AuthDashboardScheduleRouteWithChildren =
  AuthDashboardScheduleRoute._addFileChildren(
    AuthDashboardScheduleRouteChildren,
  )

interface AuthDashboardSuppliersRouteChildren {
  AuthDashboardSuppliersIdRoute: typeof AuthDashboardSuppliersIdRoute
}

const AuthDashboardSuppliersRouteChildren: AuthDashboardSuppliersRouteChildren =
  {
    AuthDashboardSuppliersIdRoute: AuthDashboardSuppliersIdRoute,
  }

const AuthDashboardSuppliersRouteWithChildren =
  AuthDashboardSuppliersRoute._addFileChildren(
    AuthDashboardSuppliersRouteChildren,
  )

interface AuthDashboardVendorsRouteChildren {
  AuthDashboardVendorsNameRoute: typeof AuthDashboardVendorsNameRoute
}

const AuthDashboardVendorsRouteChildren: AuthDashboardVendorsRouteChildren = {
  AuthDashboardVendorsNameRoute: AuthDashboardVendorsNameRoute,
}

const AuthDashboardVendorsRouteWithChildren =
  AuthDashboardVendorsRoute._addFileChildren(AuthDashboardVendorsRouteChildren)

interface AuthDashboardAdminBomRouteChildren {
  AuthDashboardAdminBomNewRoute: typeof AuthDashboardAdminBomNewRoute
  AuthDashboardAdminBomIdEditRoute: typeof AuthDashboardAdminBomIdEditRoute
}

const AuthDashboardAdminBomRouteChildren: AuthDashboardAdminBomRouteChildren = {
  AuthDashboardAdminBomNewRoute: AuthDashboardAdminBomNewRoute,
  AuthDashboardAdminBomIdEditRoute: AuthDashboardAdminBomIdEditRoute,
}

const AuthDashboardAdminBomRouteWithChildren =
  AuthDashboardAdminBomRoute._addFileChildren(
    AuthDashboardAdminBomRouteChildren,
  )

interface AuthDashboardAdminDepartmentsRouteChildren {
  AuthDashboardAdminDepartmentsNewRoute: typeof AuthDashboardAdminDepartmentsNewRoute
  AuthDashboardAdminDepartmentsIdEditRoute: typeof AuthDashboardAdminDepartmentsIdEditRoute
}

const AuthDashboardAdminDepartmentsRouteChildren: AuthDashboardAdminDepartmentsRouteChildren =
  {
    AuthDashboardAdminDepartmentsNewRoute:
      AuthDashboardAdminDepartmentsNewRoute,
    AuthDashboardAdminDepartmentsIdEditRoute:
      AuthDashboardAdminDepartmentsIdEditRoute,
  }

const AuthDashboardAdminDepartmentsRouteWithChildren =
  AuthDashboardAdminDepartmentsRoute._addFileChildren(
    AuthDashboardAdminDepartmentsRouteChildren,
  )

interface AuthDashboardAdminUsersRouteChildren {
  AuthDashboardAdminUsersNewRoute: typeof AuthDashboardAdminUsersNewRoute
  AuthDashboardAdminUsersIdEditRoute: typeof AuthDashboardAdminUsersIdEditRoute
}

const AuthDashboardAdminUsersRouteChildren: AuthDashboardAdminUsersRouteChildren =
  {
    AuthDashboardAdminUsersNewRoute: AuthDashboardAdminUsersNewRoute,
    AuthDashboardAdminUsersIdEditRoute: AuthDashboardAdminUsersIdEditRoute,
  }

const AuthDashboardAdminUsersRouteWithChildren =
  AuthDashboardAdminUsersRoute._addFileChildren(
    AuthDashboardAdminUsersRouteChildren,
  )

interface AuthDashboardRouteChildren {
  AuthDashboardDispatchRoute: typeof AuthDashboardDispatchRoute
  AuthDashboardGatePassesRoute: typeof AuthDashboardGatePassesRoute
  AuthDashboardGrnRoute: typeof AuthDashboardGrnRoute
  AuthDashboardHistoryRoute: typeof AuthDashboardHistoryRoute
  AuthDashboardInventoryRoute: typeof AuthDashboardInventoryRouteWithChildren
  AuthDashboardMarketingRequestsRoute: typeof AuthDashboardMarketingRequestsRoute
  AuthDashboardProductionRoute: typeof AuthDashboardProductionRouteWithChildren
  AuthDashboardPurchaseOrdersRoute: typeof AuthDashboardPurchaseOrdersRoute
  AuthDashboardPurchaseRequestsRoute: typeof AuthDashboardPurchaseRequestsRoute
  AuthDashboardReceiptsRoute: typeof AuthDashboardReceiptsRoute
  AuthDashboardRequestsRoute: typeof AuthDashboardRequestsRoute
  AuthDashboardScheduleRoute: typeof AuthDashboardScheduleRouteWithChildren
  AuthDashboardSuppliersRoute: typeof AuthDashboardSuppliersRouteWithChildren
  AuthDashboardVendorsRoute: typeof AuthDashboardVendorsRouteWithChildren
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardAdminBomRoute: typeof AuthDashboardAdminBomRouteWithChildren
  AuthDashboardAdminDepartmentsRoute: typeof AuthDashboardAdminDepartmentsRouteWithChildren
  AuthDashboardAdminSettingsRoute: typeof AuthDashboardAdminSettingsRoute
  AuthDashboardAdminUsersRoute: typeof AuthDashboardAdminUsersRouteWithChildren
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardDispatchRoute: AuthDashboardDispatchRoute,
  AuthDashboardGatePassesRoute: AuthDashboardGatePassesRoute,
  AuthDashboardGrnRoute: AuthDashboardGrnRoute,
  AuthDashboardHistoryRoute: AuthDashboardHistoryRoute,
  AuthDashboardInventoryRoute: AuthDashboardInventoryRouteWithChildren,
  AuthDashboardMarketingRequestsRoute: AuthDashboardMarketingRequestsRoute,
  AuthDashboardProductionRoute: AuthDashboardProductionRouteWithChildren,
  AuthDashboardPurchaseOrdersRoute: AuthDashboardPurchaseOrdersRoute,
  AuthDashboardPurchaseRequestsRoute: AuthDashboardPurchaseRequestsRoute,
  AuthDashboardReceiptsRoute: AuthDashboardReceiptsRoute,
  AuthDashboardRequestsRoute: AuthDashboardRequestsRoute,
  AuthDashboardScheduleRoute: AuthDashboardScheduleRouteWithChildren,
  AuthDashboardSuppliersRoute: AuthDashboardSuppliersRouteWithChildren,
  AuthDashboardVendorsRoute: AuthDashboardVendorsRouteWithChildren,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardAdminBomRoute: AuthDashboardAdminBomRouteWithChildren,
  AuthDashboardAdminDepartmentsRoute:
    AuthDashboardAdminDepartmentsRouteWithChildren,
  AuthDashboardAdminSettingsRoute: AuthDashboardAdminSettingsRoute,
  AuthDashboardAdminUsersRoute: AuthDashboardAdminUsersRouteWithChildren,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PwaDebugRoute: PwaDebugRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
