/**
 * https-proxy.js
 *
 * Thin HTTPS-to-HTTP reverse proxy that sits in front of Next.js (port 3000).
 *
 * Linux:   Listens on port 4443 (no root needed).
 *          start-linux.sh adds an iptables rule: 443 → 4443
 *          so the browser reaches it at https://IP (no port).
 *
 * Windows: Listens on port 443 directly (NSSM service runs as SYSTEM).
 *
 * Certificate discovery (first match wins):
 *   frontend/certs/oneflow.pfx          — Windows (generated by install.bat)
 *   frontend/certs/oneflow-cert.pem     — Linux   (generated by start-linux.sh)
 */

const https = require("https");
const http  = require("http");
const fs    = require("fs");
const path  = require("path");
const net   = require("net");

// Windows NSSM service runs as SYSTEM → can bind 443.
// Linux non-root process → bind 4443, iptables redirects 443→4443.
const HTTPS_PORT = process.env.HTTPS_PROXY_PORT ? parseInt(process.env.HTTPS_PROXY_PORT) : 4443;
const NEXT_PORT  = 3000;
const CERTS_DIR  = path.join(__dirname, "certs");

// ── Load TLS credentials ───────────────────────────────────────────────────
function loadTls() {
  const pfxPath  = path.join(CERTS_DIR, "oneflow.pfx");
  const certPath = path.join(CERTS_DIR, "oneflow-cert.pem");
  const keyPath  = path.join(CERTS_DIR, "oneflow-key.pem");

  if (fs.existsSync(pfxPath)) {
    console.log("[https-proxy] Using PFX certificate (Windows mode)");
    return { pfx: fs.readFileSync(pfxPath), passphrase: "oneflow-local" };
  }
  if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
    console.log("[https-proxy] Using PEM certificate (Linux mode)");
    return { cert: fs.readFileSync(certPath), key: fs.readFileSync(keyPath) };
  }

  console.error("[https-proxy] No certificate found in", CERTS_DIR);
  console.error("[https-proxy] Windows: run install.bat  |  Linux: run start-linux.sh");
  process.exit(1);
}

const tlsOptions = loadTls();

// ── Proxy one HTTP request ─────────────────────────────────────────────────
function handleRequest(req, res) {
  const proxyReq = http.request(
    {
      hostname: "127.0.0.1",
      port: NEXT_PORT,
      path: req.url,
      method: req.method,
      headers: { ...req.headers, host: `127.0.0.1:${NEXT_PORT}` },
    },
    (proxyRes) => {
      res.writeHead(proxyRes.statusCode, proxyRes.headers);
      proxyRes.pipe(res, { end: true });
    }
  );

  proxyReq.on("error", () => {
    if (!res.headersSent) {
      res.writeHead(502, { "Content-Type": "text/plain" });
    }
    res.end("OneFlow is starting, please wait a moment and refresh.");
  });

  req.pipe(proxyReq, { end: true });
}

// ── Proxy WebSocket upgrades ───────────────────────────────────────────────
function handleUpgrade(req, socket, head) {
  const proxySocket = net.connect(NEXT_PORT, "127.0.0.1", () => {
    proxySocket.write(
      `${req.method} ${req.url} HTTP/1.1\r\n` +
      Object.entries(req.headers).map(([k, v]) => `${k}: ${v}`).join("\r\n") +
      "\r\n\r\n"
    );
    proxySocket.write(head);
  });
  proxySocket.pipe(socket);
  socket.pipe(proxySocket);
  proxySocket.on("error", () => socket.destroy());
  socket.on("error",      () => proxySocket.destroy());
}

// ── Start ──────────────────────────────────────────────────────────────────
const server = https.createServer(tlsOptions, handleRequest);
server.on("upgrade", handleUpgrade);

server.listen(HTTPS_PORT, "0.0.0.0", () => {
  console.log(`[https-proxy] Listening on :${HTTPS_PORT} → http://127.0.0.1:${NEXT_PORT}`);
  if (HTTPS_PORT !== 443) {
    console.log(`[https-proxy] Expecting iptables redirect: 443 → ${HTTPS_PORT}`);
  }
});

server.on("error", (err) => {
  if (err.code === "EADDRINUSE") {
    console.error(`[https-proxy] Port ${HTTPS_PORT} in use. Run stop-linux.sh or stop.bat first.`);
  } else {
    console.error("[https-proxy] Error:", err.message);
  }
  process.exit(1);
});
