import { useEffect } from "react"

/**
 * Registers the service worker generated by vite-plugin-pwa.
 * Client-only (SSR-safe): the virtual module import happens lazily
 * inside the effect so the server bundle never touches it.
 */
export function PwaRegister() {
  useEffect(() => {
    void import("virtual:pwa-register").then(({ registerSW }) => {
      registerSW({
        immediate: true,
        onNeedRefresh() {
          // New version available — reload to pick it up (autoUpdate keeps SW current).
        },
        onOfflineReady() {
          // App is ready to work offline.
        },
      })
    })
  }, [])
  return null
}
