# Models package — import all table models here so SQLModel.metadata is populated
from app.models.bom_item import BomItem  # noqa: F401
from app.models.company_settings import CompanySettings  # noqa: F401
from app.models.consumable import Consumable  # noqa: F401
from app.models.consumable_history import ConsumableHistory  # noqa: F401
from app.models.vendor import Vendor  # noqa: F401
from app.models.supplier import Supplier  # noqa: F401
from app.models.document_counter import DocumentCounter  # noqa: F401
from app.models.department import Department  # noqa: F401
from app.models.inventory import InventoryItem  # noqa: F401
from app.models.inventory_history import InventoryHistory  # noqa: F401
from app.models.job_card import JobCard  # noqa: F401
from app.models.job_card_history import JobCardHistory  # noqa: F401
from app.models.production_order import ProductionOrder  # noqa: F401
from app.models.production_plan import ProductionPlan  # noqa: F401
from app.models.production_process import ProductionProcess  # noqa: F401
from app.models.schedule import Schedule  # noqa: F401
from app.models.schedule_history import ScheduleHistory  # noqa: F401
from app.models.grn import GRNRecord  # noqa: F401
from app.models.grn_item import GRNItem  # noqa: F401
from app.models.token import RefreshToken  # noqa: F401
from app.models.user import User  # noqa: F401
from app.models.user_department import UserDepartment  # noqa: F401
from app.models.spare_category import SpareCategory  # noqa: F401
from app.models.spare_sub_category import SpareSubCategory  # noqa: F401  — must be before SpareItem
from app.models.spare_item import SpareItem  # noqa: F401
from app.models.spare_item_history import SpareItemHistory  # noqa: F401
from app.models.spare_item_variant import SpareItemVariant  # noqa: F401
from app.models.work_log import WorkLog  # noqa: F401
from app.models.work_type import WorkType  # noqa: F401
from app.models.attachment_item import AttachmentItem  # noqa: F401
from app.models.attachment_document import AttachmentDocument  # noqa: F401
from app.models.attachment_history import AttachmentHistory  # noqa: F401
from app.models.weeder_category import WeederCategory  # noqa: F401  — must be before WeederItem
from app.models.weeder_item import WeederItem  # noqa: F401
from app.models.weeder_history import WeederHistory  # noqa: F401
from app.models.purchase_request import PurchaseRequest  # noqa: F401
from app.models.purchase_request_history import PurchaseRequestHistory  # noqa: F401
from app.models.marketing_request import MarketingRequest  # noqa: F401
from app.models.marketing_request_history import MarketingRequestHistory  # noqa: F401
from app.models.request import Request  # noqa: F401
from app.models.request_customer_dispatch import RequestCustomerDispatch  # noqa: F401
from app.models.request_history import RequestHistory  # noqa: F401
from app.models.request_item import RequestItem  # noqa: F401
from app.models.notification import Notification  # noqa: F401
from app.models.dispatch import Dispatch  # noqa: F401
from app.models.dispatch_item import DispatchItem  # noqa: F401
from app.models.dispatch_history import DispatchHistory  # noqa: F401
from app.models.gate_pass import GatePass  # noqa: F401
from app.models.gate_pass_item import GatePassItem  # noqa: F401
from app.models.gate_pass_history import GatePassHistory  # noqa: F401
from app.models.purchase_order import PurchaseOrder, PurchaseOrderItem  # noqa: F401
from app.models.purchase_request_item import PurchaseRequestItem  # noqa: F401
from app.models.receipt import Receipt  # noqa: F401
from app.models.receipt_item import ReceiptItem  # noqa: F401
from app.models.supplier_job import SupplierJob  # noqa: F401
from app.models.supplier_material import SupplierMaterial  # noqa: F401
from app.models.unit import Unit  # noqa: F401
