/**
 * detect-backend.js
 *
 * Detects the machine's local LAN IP and writes it to frontend/.env.local
 * so the Next.js app points to the correct backend URL automatically.
 *
 * Run manually:  node scripts/detect-backend.js
 * Called automatically via:  npm run prebuild / npm run predev
 */

const os = require("os");
const fs = require("fs");
const path = require("path");

const BACKEND_PORT = 8000;
const ENV_FILE = path.join(__dirname, "..", ".env.local");

/**
 * Returns the first non-loopback IPv4 address found on this machine.
 * Falls back to "localhost" if nothing is found.
 */
function getLocalIP() {
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const iface of ifaces[name]) {
      if (iface.family === "IPv4" && !iface.internal) {
        return iface.address;
      }
    }
  }
  return "localhost";
}

const ip = getLocalIP();
const backendUrl = `http://${ip}:${BACKEND_PORT}`;

const envContent = [
  `# Auto-generated by scripts/detect-backend.js — do not edit manually`,
  `NEXT_PUBLIC_API_URL=${backendUrl}`,
  ``,
].join("\n");

fs.writeFileSync(ENV_FILE, envContent, "utf8");
console.log(`[detect-backend] Backend URL set to: ${backendUrl}`);
console.log(`[detect-backend] Written to: ${ENV_FILE}`);
