/**
 * detect-backend.js
 *
 * Detects the machine's local LAN IP and writes it to frontend/.env.local
 * so the Next.js app points to the correct backend URL automatically.
 *
 * - Uses https:// when certs/oneflow-cert.pem exists (HTTPS proxy is active)
 * - Falls back to http://:8000 otherwise
 *
 * Run manually:  node scripts/detect-backend.js
 * Called automatically via:  npm run prebuild / npm run predev
 */

const os   = require("os");
const fs   = require("fs");
const path = require("path");

const BACKEND_PORT = 8000;
const CERT_FILE    = path.join(__dirname, "..", "certs", "oneflow-cert.pem");
const ENV_FILE     = path.join(__dirname, "..", ".env.local");

function getLocalIP() {
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const iface of ifaces[name]) {
      if (iface.family === "IPv4" && !iface.internal) {
        return iface.address;
      }
    }
  }
  return "localhost";
}

const ip          = getLocalIP();
const hasHttps    = fs.existsSync(CERT_FILE) || fs.existsSync(path.join(__dirname, "..", "certs", "oneflow.pfx"));
// HTTPS proxy listens on 443 (no port in URL); HTTP falls back to 8000
const backendUrl  = hasHttps
  ? `https://${ip}`         // port 443, omitted from URL
  : `http://${ip}:${BACKEND_PORT}`;

const envContent = [
  `# Auto-generated by scripts/detect-backend.js — do not edit manually`,
  `NEXT_PUBLIC_API_URL=${backendUrl}`,
  ``,
].join("\n");

fs.writeFileSync(ENV_FILE, envContent, "utf8");
console.log(`[detect-backend] Backend URL set to: ${backendUrl}${hasHttps ? "  (HTTPS)" : "  (HTTP — PWA will not work as standalone)"}`);
console.log(`[detect-backend] Written to: ${ENV_FILE}`);
